save="/mnt/ws-frb/projects/thermal_rgb/files_miracle_sharing_with_nitin/post_processing/"  #note the '/' is at end
copy_from_base="/home/akanu/akanu/projects/fusion_therm_rgb/state-of-art-detectors/multispectral-video-object-detection/" #note the '/' is at end

paths_to_create_kaist="runs/test/yolov5l_kaist_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze
runs/test/yolov5l_kaist_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze_backbone
runs/test/yolov5l_kaist_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T
runs/test/yolov5l_kaist_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T
runs/test/yolov5l_kaist_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_R_iT_freezeT
runs/test/yolov5l_kaist_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_R_iT_freezeT
runs/test/yolov5l_kaist_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T
runs/test/yolov5l_kaist_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T
runs/test/yolov5l_kaist_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_R_iT_freezeT
runs/test/yolov5l_kaist_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_R_iT_freezeT
runs/test/yolov5l_kaist_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T
runs/test/yolov5l_kaist_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T 
runs/test/yolov5l_kaist_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T_3_temporal_stride_7_lframe
runs/test/yolov5l_kaist_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T_3_temporal_stride_7_lframe
runs/test/yolov5l_kaist_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T_3_temporal_stride_5_lframe
runs/test/yolov5l_kaist_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T_3_temporal_stride_5_lframe
"



paths_to_create_cvc14="runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze_backbone
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_R_iT_freezeT
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_R_iT_freezeT
runs/test/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T
runs/test/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T
runs/test/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_R_iT_freezeT
runs/test/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_R_iT_freezeT
runs/test/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_no_freezing
runs/test/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_no_freezing
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T_3_temporal_stride_7_lframe
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T_3_temporal_stride_7_lframe
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T_3_temporal_stride_5_lframe
runs/test/yolov5l_cvc14_tadaconv_stripmlpSTmixv2_lastframe_2DH_no_kl_div_freeze3_init_bb_both_heads_iR_freezeR_iT_T_3_temporal_stride_5_lframe
"

for i in $paths_to_create_kaist; do
    mkdir -p "${save}${i}"
    done

for i in $paths_to_create_cvc14; do
    mkdir -p "${save}${i}"
    done

for i in $paths_to_create_kaist; do
    cp "${copy_from_base}${i}/cur_24_predictions_ct2_all.json" "${save}${i}/cur_24_predictions_ct2_all.json"
    done


for i in $paths_to_create_cvc14; do
    cp "${copy_from_base}${i}/cur_39_predictions_ct2_rgb.json" "${save}${i}/cur_39_predictions_ct2_rgb.json"
    done