here="mlpSTmixv2_tadaconv_thermal_rgb_backbone_head_rgb_lframe_3_stride_3_drop_25_diff_patches_fullframes
mlpSTmixv2_tadaconv_thermal_rgb_backbone_head_rgb_lframe_3_stride_3_drop_25_diff_patches_fullframes
mlpSTmixv2_tadaconv_thermal_rgb_backbone_head_rgb_lframe_3_stride_3_drop_25_diff_patches_fullframes
mlpSTmixv2_tadaconv_thermal_rgb_backbone_head_rgb_lframe_3_stride_3_drop_25_diff_patches_focal_fullframes
mlpSTmixv2_tadaconv_thermal_rgb_backbone_head_blank_lframe_3_stride_3_drop_25_fullframes
mlpSTmixv2_tadaconv_thermal_rgb_backbone_head_blank_lframe_3_stride_3_drop_25_focal_fullframes
mlpSTmixv2_tadaconv_thermal_rgb_backbone_head_blank_lframe_3_stride_3_drop_25_diff_patches_fullframes
mlpSTmixv2_tadaconv_thermal_rgb_backbone_head_blank_lframe_3_stride_3_drop_25_diff_patches_focal_fullframes
"

for i in $here; do
    echo $i
    done