# runs/train/yolov5l_kaist_with_tadaconv_stripmlpSTmixv2_lastframe_2DH_without_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe
# runs/train/yolov5l_kaist_with_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_2_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe
# runs/train/yolov5l_kaist_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_without_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe
# runs/train/yolov5l_kaist_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_2_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe

# yolov5l_kaist_with_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_2_freeze3_init_bb_both_heads_iR_freezeR_iT_T_1_tstride_1_lframe_fixed_kl_div

python miss_rate_and_map/evaluation_script.py \
 --annFile miss_rate_and_map/KAIST_annotation.json \
 --rstFiles runs/test/yolov5l_kaist_with_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_2_freeze3_init_bb_both_heads_iR_freezeR_iT_T_1_tstride_1_lframe_fixed_kl_div/cur_24_predictions_ct2_conf_all.json \
            runs/test/yolov5l_kaist_with_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_2_freeze3_init_bb_both_heads_iR_freezeR_iT_T_1_tstride_1_lframe_fixed_kl_div/cur_24_predictions_ct2_conf_rgb.json \
            runs/test/yolov5l_kaist_with_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_2_freeze3_init_bb_both_heads_iR_freezeR_iT_T_1_tstride_1_lframe_fixed_kl_div/cur_24_predictions_ct2_conf_thermal.json \
            runs/test/yolov5l_kaist_with_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_2_freeze3_init_bb_both_heads_iR_freezeR_iT_T_1_tstride_1_lframe_fixed_kl_div/cur_24_predictions_ct2_all_pp_fusion.json
