# runs/train/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_3_tstride_3_lframe_ablation_why_w_o_tadaconv_worst
# runs/train/yolov5l_cvc14_with_tadaconv_stripmlpSTmixv2_lastframe_2DH_without_kl_div_freeze3_init_bb_both_heads_iR_R_iT_freezeT_1_tstride_1_lframe_fixed_kl_div_cvc14_use_only_rgb_anns_verify_again
#runs/train/yolov5l_cvc14_with_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe_fixed_kl_div_cvc14_use_only_rgb_anns
# runs/train/yolov5l_cvc14_with_tadaconv_stripmlpSTmixv2_lastframe_2DH_without_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe_fixed_cvc14_use_only_rgb_anns
# runs/train/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_without_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe_fixed_cvc14_use_only_rgb_anns
# runs/train/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe_fixed_cvc14_use_only_rgb_anns

python miss_rate_and_map/evaluation_script_cvc14.py \
 --annFile json_gt/cvc-14_test_tl.json \
 --rstFiles runs/test/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe_fixed_cvc14_use_only_rgb_anns/cur_39_predictions_ct2_conf_all.json \
            runs/test/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe_fixed_cvc14_use_only_rgb_anns/cur_39_predictions_ct2_conf_rgb.json \
            runs/test/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe_fixed_cvc14_use_only_rgb_anns/cur_39_predictions_ct2_conf_thermal.json \
            runs/test/yolov5l_cvc14_without_tadaconv_stripmlpSTmixv2_lastframe_2DH_with_kl_div_no_freezing_init_bb_both_heads_iR_R_iT_T_1_tstride_1_lframe_fixed_cvc14_use_only_rgb_anns/cur_39_predictions_ct2_conf_all_pp_fusion.json